description: A new Flutter application.
name: mobile_prototype
publish_to: 'none'
version: "1.0.0+1"
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^0.1.3
  path_drawing: ^0.4.1+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  shared_preferences: ^0.5.6+2
  provider: ^4.3.2+2
  google_sign_in: ^4.5.6

dev_dependencies: 
  flutter_test: 
    sdk: flutter
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - assets/images/
  fonts: 
    - 
      family: "Lato"
      fonts: 
        - 
          asset: "fonts/Lato-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Lato-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-500.ttf"
          style: "normal"
          weight: 500
  uses-material-design: true
